spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka:9092
    properties:
      security.protocol: PLAINTEXT

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9093  # Используем порт 9093 для доступа с хоста
    properties:
      security.protocol: PLAINTEXT

---
# Общие настройки
spring:
  application:
    name: chat-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: chatuser
    password: chatpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  profiles:
    active: local  # По умолчанию используем local профиль

server:
  port: 8081

logging:
  level:
    com.j0schi: DEBUG
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG